/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductRouteImport } from './routes/product'
import { Route as OccasionsRouteImport } from './routes/occasions'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CraftRouteImport } from './routes/craft'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsRoute = OccasionsRouteImport.update({
  id: '/occasions',
  path: '/occasions',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftRoute = CraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/create': typeof CreateRoute
  '/founder': typeof FounderRoute
  '/gallery': typeof GalleryRoute
  '/occasions': typeof OccasionsRoute
  '/product': typeof ProductRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/create': typeof CreateRoute
  '/founder': typeof FounderRoute
  '/gallery': typeof GalleryRoute
  '/occasions': typeof OccasionsRoute
  '/product': typeof ProductRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/create': typeof CreateRoute
  '/founder': typeof FounderRoute
  '/gallery': typeof GalleryRoute
  '/occasions': typeof OccasionsRoute
  '/product': typeof ProductRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/contact'
    | '/craft'
    | '/create'
    | '/founder'
    | '/gallery'
    | '/occasions'
    | '/product'
    | '/sitemap.xml'
    | '/stories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/contact'
    | '/craft'
    | '/create'
    | '/founder'
    | '/gallery'
    | '/occasions'
    | '/product'
    | '/sitemap.xml'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/contact'
    | '/craft'
    | '/create'
    | '/founder'
    | '/gallery'
    | '/occasions'
    | '/product'
    | '/sitemap.xml'
    | '/stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  CraftRoute: typeof CraftRoute
  CreateRoute: typeof CreateRoute
  FounderRoute: typeof FounderRoute
  GalleryRoute: typeof GalleryRoute
  OccasionsRoute: typeof OccasionsRoute
  ProductRoute: typeof ProductRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions': {
      id: '/occasions'
      path: '/occasions'
      fullPath: '/occasions'
      preLoaderRoute: typeof OccasionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft': {
      id: '/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof CraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  CraftRoute: CraftRoute,
  CreateRoute: CreateRoute,
  FounderRoute: FounderRoute,
  GalleryRoute: GalleryRoute,
  OccasionsRoute: OccasionsRoute,
  ProductRoute: ProductRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
